# Generated by Django 3.0.2 on 2020-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsterLeague', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SH', 'Scheduled'), ('FI', 'Finished')], default='SH', max_length=2),
        ),
    ]
