# Generated by Django 3.0.2 on 2020-01-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TipsterLeague', '0004_auto_20200115_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('status', models.CharField(choices=[('SH', 'Scheduled'), ('FI', 'Finished')], default='SH', max_length=2)),
                ('gameweek', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipsterLeague.Competition')),
            ],
        ),
    ]
