# Generated by Django 3.0.2 on 2020-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsterLeague', '0007_competition_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='theme_color_hex',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
