# Generated by Django 3.0.2 on 2020-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsterLeague', '0008_competition_theme_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='theme_color_hex',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
