# Generated by Django 3.0.2 on 2020-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipsterLeague', '0012_auto_20200121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='emblem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='theme_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
